apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: szlqtss1k-python 
  janus-idp.io/tekton: szlqtss1k-python
  backstage.io/kubernetes-id: szlqtss1k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: szlqtss1k-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  